# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

afBpDiffCdf <- function(a, b, gen, paramsList) {
    .Call('_fluodilution_afBpDiffCdf', PACKAGE = 'fluodilution', a, b, gen, paramsList)
}

modelBranchingInit <- function(params, startPop, Gm, times, initial, verbose = TRUE) {
    .Call('_fluodilution_modelBranchingInit', PACKAGE = 'fluodilution', params, startPop, Gm, times, initial, verbose)
}

modelBranchingRelease <- function(obj) {
    invisible(.Call('_fluodilution_modelBranchingRelease', PACKAGE = 'fluodilution', obj))
}

modelBranching <- function(params, obj) {
    .Call('_fluodilution_modelBranching', PACKAGE = 'fluodilution', params, obj)
}

cytonConv <- function(x, y) {
    .Call('_fluodilution_cytonConv', PACKAGE = 'fluodilution', x, y)
}

